name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:

env:
  DOPPLER_TOKEN_PROJECT: ${{ secrets.DOPPLER_TOKEN_PRODUCTION_PROJECT }}
  DOPPLER_TOKEN_ROOT: ${{ secrets.DOPPLER_TOKEN_PRODUCTION_ROOT }}
  DOPPLER_TOKEN_TEST: ${{ secrets.DOPPLER_TOKEN_TEST_PROJECT }}

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [14.x]        

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - name: Install Doppler CLI
  #     uses: dopplerhq/cli-action@v1     

  #   - name: Pass all secrets to test
  #     env:
  #       DOPPLER_TOKEN: ${{ env.DOPPLER_TOKEN_TEST }}
  #     run: doppler secrets download --no-file --format env-no-quotes >> $GITHUB_ENV; 

  #   - run: npm ci
  #   - run: npm run build --if-present
  #   - run: npm test

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]        

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Doppler CLI
      uses: dopplerhq/cli-action@v1

    - name: get env project
      run: doppler secrets download -t ${{ env.DOPPLER_TOKEN_PROJECT }} --no-file --format env-no-quotes >> .env.project;

    - name: get env root
      run: doppler secrets download -t ${{ env.DOPPLER_TOKEN_ROOT }} --no-file --format env-no-quotes >> .env.deploy;

    - name: import to env
      run: |
        cat .env.deploy >> $GITHUB_ENV;
        cat .env.project >> $GITHUB_ENV;

    - uses: kciter/aws-ecr-action@master
      with:
        access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ env.AWS_ACCOUNT_ID }}
        repo: ${{ env.ECR_REPOSITORY_NAME }}
        region: ${{ env.ECR_REGION }}
        tags: latest-${{ env.ENV }},${{ github.sha }}
        create_repo: true

    - name: "set service url"
      run: |
        if [ ${ENV} == "production" ]
        then
          export SERVICE_URL="${SERVICE_URL}"
        else
          export SERVICE_URL="${ENV}.${SERVICE_URL}"
        fi

    - name: "get cluster ip"
      env:
        CLUSTER_SERVER: ${{ fromJSON(env.KUBE_CONFIG).clusters[0].cluster.server }}
      run: |
        export CLUSTER_IP=$(echo $CLUSTER_SERVER | cut -d'/' -f 3 | cut -d':' -f 1)
        echo "CLUSTER_IP=${CLUSTER_IP}" >> $GITHUB_ENV
        echo $CLUSTER_IP

    - name: "Create an A record set"
      uses: Roosterfish/aws-route53-record-set-action@master
      with: 
        aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws_route53_hosted_zone_id: ${{ env.AWS_HOSTED_ZONE_ID }}
        aws_route53_rr_action: "UPSERT"
        aws_route53_rr_name: ${{ env.SERVICE_URL }}
        aws_route53_rr_type: "A"
        aws_route53_rr_ttl: "300"
        aws_route53_rr_value: ${{ env.CLUSTER_IP }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [14.x]        

    steps:
    - uses: actions/checkout@v2
    - name: Install Doppler CLI
      uses: dopplerhq/cli-action@v1

    - name: get env project
      run: doppler secrets download -t ${{ env.DOPPLER_TOKEN_PROJECT }} --no-file --format env-no-quotes >> .env.project;

    - name: get env root
      run: doppler secrets download -t ${{ env.DOPPLER_TOKEN_ROOT }} --no-file --format env-no-quotes >> .env.deploy;

    - name: import to env
      run: |
        cat .env.deploy >> $GITHUB_ENV;
        cat .env.project >> $GITHUB_ENV;

    - name: Config kubernetes
      uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ env.KUBE_CONFIG }}

    - name: Prepare env
      run: |
        export IMAGE_REPO_URL=${AWS_ACCOUNT_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${{ github.sha }}
        export CERT_MANAGER_ISSUE_TEMPORARY_CERTICATE="false"
        export INGRESS_EDIT_IN_PLACE="false"
        echo "IMAGE_REPO_URL=${IMAGE_REPO_URL}" >> $GITHUB_ENV
        echo "CERT_MANAGER_ISSUE_TEMPORARY_CERTICATE=${CERT_MANAGER_ISSUE_TEMPORARY_CERTICATE}" >> $GITHUB_ENV
        echo "INGRESS_EDIT_IN_PLACE=${INGRESS_EDIT_IN_PLACE}" >> $GITHUB_ENV

    - name: create namespace
      run: |
        cat << EOF | kubectl apply -f -
        apiVersion: v1
        kind: Namespace
        metadata:
          name: $K8S_NAMESPACE
        EOF

    - name: Create Secret kubernetes
      run: |
        kubectl delete secret $SERVICE_NAME --namespace $K8S_NAMESPACE --ignore-not-found
        kubectl create secret generic $SERVICE_NAME --from-env-file=.env.project --namespace $K8S_NAMESPACE

    - name: Create image pull secrets kubernetes
      run: |
        kubectl delete secret $IMAGE_PULL_SECRET --namespace ${{ env.K8S_NAMESPACE }} --ignore-not-found
        TOKEN=`aws ecr get-login-password --region ${{ env.ECR_REGION }}`
        kubectl create secret docker-registry $IMAGE_PULL_SECRET \
          --docker-username AWS \
          --docker-server ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.ECR_REGION }}.amazonaws.com \
          --docker-email anymail.doesnt.matter@email.local \
          --docker-password $TOKEN \
          -n ${{ env.K8S_NAMESPACE }}

    - uses: danielr1996/envsubst-action@1.0.0
      with:
        input: .infra/deployment.yaml
        output: .infra/output.yaml

    - name: apply manifests
      run: |
        kubectl apply -f .infra/output.yaml
